/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedMensagensRouteImport } from './routes/_authenticated/mensagens'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCobrancasRouteImport } from './routes/_authenticated/cobrancas'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'

const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/_authenticated/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMensagensRoute = AuthenticatedMensagensRouteImport.update({
  id: '/_authenticated/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/_authenticated/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCobrancasRoute = AuthenticatedCobrancasRouteImport.update({
  id: '/_authenticated/cobrancas',
  path: '/cobrancas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/_authenticated/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/clientes': typeof AuthenticatedClientesRoute
  '/cobrancas': typeof AuthenticatedCobrancasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
}
export interface FileRoutesByTo {
  '/clientes': typeof AuthenticatedClientesRoute
  '/cobrancas': typeof AuthenticatedCobrancasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/cobrancas': typeof AuthenticatedCobrancasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/mensagens': typeof AuthenticatedMensagensRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/clientes'
    | '/cobrancas'
    | '/configuracoes'
    | '/dashboard'
    | '/mensagens'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clientes'
    | '/cobrancas'
    | '/configuracoes'
    | '/dashboard'
    | '/mensagens'
    | '/relatorios'
  id:
    | '__root__'
    | '/_authenticated/clientes'
    | '/_authenticated/cobrancas'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/mensagens'
    | '/_authenticated/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedCobrancasRoute: typeof AuthenticatedCobrancasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMensagensRoute: typeof AuthenticatedMensagensRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mensagens': {
      id: '/_authenticated/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof AuthenticatedMensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cobrancas': {
      id: '/_authenticated/cobrancas'
      path: '/cobrancas'
      fullPath: '/cobrancas'
      preLoaderRoute: typeof AuthenticatedCobrancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedCobrancasRoute: AuthenticatedCobrancasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMensagensRoute: AuthenticatedMensagensRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
